### PR TITLE
Rework metrics examples

### PR DESCRIPTION
**Pull request by breedx-splk**
I lost track of the fact that I had already submitted the histogram example. So anyway, this updates it a little bit to include custom buckets. I'm not stoked on the cast required in the bucket example, but I think it's all we have right now. Happy to remove it if we think it's premature.

I also changed the other examples to use the autoconfigured SDK so that folks can actually run them in their IDE without getting the noop implementations.

### CODE REVIEW

**Comment by mateuszrzeszutek** [comment]
> Happy to remove it if we think it's premature.

Could we wait for stabilizing it? There is already an issue in the spec about stabilizing it (https://github.com/open-telemetry/opentelemetry-specification/issues/3391), I think it should be done before the javaagent 2.0 release.

**Comment by breedx-splk** [comment]
That's cool. Let's just sit on the PR then for a bit and if it gets too stale I'll update or recreate it. 👍🏻

**Comment by breedx-splk** [comment]
Would it feel ok if the thing just had a big javadoc disclaimer about this feature not being stable yet?

**Comment by mateuszrzeszutek** [comment]
> Would it feel ok if the thing just had a big javadoc disclaimer about this feature not being stable yet?

Hmm, I think so? I think I would be okay with that as long as we're very clear that this is an incubating API, and not yet stable.

**Pull request merged**
